apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myserver
spec:
  replicas: 5
  template:
    metadata:
      labels:
        service: myserver
    spec:
      containers:
      - name: main
        command: ["/bin/bash", "-c", "sleep 10; touch /run/RUNNING ; while true ; do sleep 1 ; data ; done"]
        image: ubuntu:16.04
        livenessProbe:
          exec:
            command:
              - cat /run/RUNNING
          initialDelaySeconds: 5
          periodSeconds: 1
