apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myserver-app
spec:
  replicas: 5
  template:
    metadata:
      labels:
        service: myserver-app
        "watch-initContainer-logs": "true"
    spec:
      initContainers:
      - name: init
        command: ["/bin/bash", "-c", "for i in {1..15}; do echo init - $(date) ; sleep 1 ; done"]
        image: ubuntu:16.04
      containers:
      - name: one
        image: ubuntu:16.04
      - name: two
        command: ["/bin/bash", "-c", "while true ; do date ; sleep 1 ; done"]
        image: ubuntu:16.04
---
apiVersion: batch/v1
kind: Job
metadata:
  name: myserver-migrate-hook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "dapp/watch-logs": "true"
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: myserver-migrate-hook
    spec:
      restartPolicy: Never
      containers:
      - name: myserver-migrate-hook
        command: ["/bin/bash", "-c", "echo MIGRATING ... ; echo . ; sleep 1 ; echo . ; sleep 1; echo MIGRATION DONE!"]
        image: ubuntu:16.04
---
apiVersion: batch/v1
kind: Job
metadata:
  name: myserver-initcontainer-log
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "dapp/watch-logs": "true"
spec:
  activeDeadlineSeconds: 100
  template:
    metadata:
      name: myserver-initcontainer-log
    spec:
      restartPolicy: Never
      containers:
      - name: myserver-initcontainer-log
        command: ["/bin/bash", "-ec", 'for pod in $(kubectl get pod  -l="watch-initContainer-logs=true" -o="custom-columns=:metadata.name" --no-headers=true) ; do echo "# $pod initContainer \"init\"" ; kubectl logs $pod -c init -f ; done']
{{ tuple "kubectl" . | include "dapp_container_image" | indent 8 }}
        env:
{{ tuple "kubectl" . | include "dapp_container_env" | indent 10 }}
